[package]
name = "tilr"
description = "Build a mosaic of a particular image out of a set of smaller images."
version = "0.1.0"
authors = ["Charles German <5donuts@protonmail.com>"]
edition = "2018"
readme = "./README.md"
license = "GPL-3.0-or-later"
homepage = "https://github.com/5donuts/tilr"
categories = ["multimedia::images"]
keywords = ["image-processing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
structopt = "0.3"
